from __future__ import annotations

import json
import os
import re
import subprocess
import urllib.error
import urllib.request
from datetime import datetime, timezone
from typing import TYPE_CHECKING

from .config import get_provider

if TYPE_CHECKING:
    from .providers.base import BaseProvider
    from .tools import ToolCall


_ANALYSIS_SYSTEM_PROMPT = """You are an expert at analyzing AI agent failures and generating test criteria.

Given an agent execution (user message, response, error, metrics, tool calls), identify:
1. What went wrong — concise, human-readable
2. A judge criterion that would catch this failure in future runs
3. Whether a no_errors() check is appropriate (true if an error was present)
4. Whether a latency check is appropriate (true if elapsed_time is present and suspiciously high)

Be specific in the judge criterion — it should describe the correct behavior, not just "no errors".

Return JSON only — no extra text, no markdown fences:
{"failure_description": string, "judge_criterion": string, "include_no_errors": bool, "include_latency": bool, "latency_threshold": float | null}"""

_ANALYSIS_USER_TEMPLATE = """User message:
{user_message}

Agent response:
{response}

Error: {error}

Metrics: {metrics}

Tool calls: {tool_calls}

Analyze this execution and return JSON describing what went wrong and what assertions would catch it."""

_TEST_TEMPLATE = '''\
# Regression test — generated by trial
# Session: {session_comment}
# Failure: {failure_description}
#
# Replace `your_agent(USER_MSG)` with your actual agent call before running.

from trial import Trial, configure
from trial.providers import AnthropicProvider

configure(provider=AnthropicProvider(model="claude-sonnet-4-6"))

USER_MSG = {user_message_repr}


def {test_fn_name}():
    response = your_agent(USER_MSG)  # TODO: replace with your agent

    result = (
        Trial.from_execution(
            user_message=USER_MSG,
            response=response,
        )
{checks}\
        .passes_judge(
            {judge_criterion_repr}
        )
        .run()
    )
    result.assert_passed()
'''


def _safe_id(session_id: str | None) -> str:
    if not session_id:
        return "session"
    return re.sub(r"[^a-zA-Z0-9]", "_", session_id)


def _unique_branch_suffix() -> str:
    """UTC timestamp suffix for collision-safe branch names."""
    return datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")


def _render_test(
    user_message: str,
    session_id: str | None,
    failure_description: str,
    judge_criterion: str,
    include_no_errors: bool,
    include_latency: bool,
    latency_threshold: float | None,
) -> str:
    checks = ""
    if include_no_errors:
        checks += "        .no_errors()\n"
    if include_latency and latency_threshold is not None:
        checks += f"        .completes_within({latency_threshold})\n"

    return _TEST_TEMPLATE.format(
        session_comment=session_id or "unknown",
        failure_description=failure_description,
        user_message_repr=repr(user_message),
        test_fn_name=f"test_regression_{_safe_id(session_id)}",
        checks=checks,
        judge_criterion_repr=repr(judge_criterion),
    )


def _get_github_repo(repo_path: str) -> tuple[str, str]:
    """Parse owner and repo name from the git remote origin URL."""
    result = subprocess.run(
        ["git", "remote", "get-url", "origin"],
        cwd=repo_path,
        capture_output=True,
        text=True,
        check=True,
    )
    url = result.stdout.strip()
    m = re.match(r"https://github\.com/([^/]+)/([^/]+?)(?:\.git)?$", url)
    if m:
        return m.group(1), m.group(2)
    m = re.match(r"git@github\.com:([^/]+)/([^/]+?)(?:\.git)?$", url)
    if m:
        return m.group(1), m.group(2)
    raise ValueError(f"Could not parse GitHub owner/repo from remote URL: {url!r}")


def _git(args: list[str], repo_path: str) -> str:
    try:
        result = subprocess.run(
            ["git"] + args,
            cwd=repo_path,
            capture_output=True,
            text=True,
            check=True,
        )
        return result.stdout.strip()
    except subprocess.CalledProcessError as e:
        raise RuntimeError(
            f"git {' '.join(args)} failed: {e.stderr.strip() or e.stdout.strip()}"
        ) from e


def _create_github_pr(
    owner: str,
    repo: str,
    token: str,
    head: str,
    base: str,
    title: str,
    body: str,
) -> str:
    """Create a GitHub PR via the REST API and return the PR URL."""
    url = f"https://api.github.com/repos/{owner}/{repo}/pulls"
    payload = json.dumps({"title": title, "head": head, "base": base, "body": body}).encode()
    req = urllib.request.Request(
        url,
        data=payload,
        headers={
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        },
    )
    try:
        with urllib.request.urlopen(req) as resp:
            data = json.loads(resp.read())
    except urllib.error.HTTPError as e:
        body_text = e.read().decode(errors="replace")
        raise RuntimeError(
            f"GitHub API error {e.code}: {body_text}"
        ) from e
    return data["html_url"]


def generate_regression_test(
    user_message: str,
    response: str,
    *,
    session_id: str | None = None,
    metrics: dict[str, float] | None = None,
    tool_calls: list | None = None,
    error: str | Exception | None = None,
    provider: BaseProvider | None = None,
    output_path: str | None = None,
) -> str:
    """Analyze a failed execution and generate a pytest regression test.

    Uses an LLM to understand what went wrong and produce appropriate
    assertions. Returns the generated test source as a string.

    Args:
        user_message: The original input sent to the agent.
        response: The agent's response text.
        session_id: Optional identifier included in the test name and header comment.
        metrics: Optional timing metrics (e.g. {"elapsed_time": 12.4}).
        tool_calls: Optional list of ToolCall objects from the execution.
        error: Optional error that occurred during execution.
        provider: LLM provider for analysis. Falls back to configure(provider=...).
        output_path: If given, write the generated file to this path.

    Returns:
        The generated Python test source as a string.
    """
    error_str: str | None = str(error) if error is not None else None
    provider = provider or get_provider()

    tool_calls_summary = (
        [{"name": tc.name, "input": tc.input} for tc in tool_calls]
        if tool_calls
        else []
    )

    user_prompt = _ANALYSIS_USER_TEMPLATE.format(
        user_message=user_message,
        response=response,
        error=error_str or "none",
        metrics=json.dumps(metrics or {}),
        tool_calls=json.dumps(tool_calls_summary),
    )

    raw = provider.complete(system=_ANALYSIS_SYSTEM_PROMPT, user=user_prompt)

    try:
        data = json.loads(raw)
    except json.JSONDecodeError as e:
        raise ValueError(f"Analysis returned malformed JSON: {e}\nRaw: {raw!r}")

    required = {"failure_description", "judge_criterion", "include_no_errors", "include_latency"}
    missing = required - data.keys()
    if missing:
        raise ValueError(f"Analysis response missing fields: {missing}\nRaw: {raw!r}")

    code = _render_test(
        user_message=user_message,
        session_id=session_id,
        failure_description=str(data["failure_description"]),
        judge_criterion=str(data["judge_criterion"]),
        include_no_errors=bool(data["include_no_errors"]),
        include_latency=bool(data["include_latency"]),
        latency_threshold=data.get("latency_threshold"),
    )

    if output_path:
        with open(output_path, "w") as f:
            f.write(code)

    return code


def create_regression_pr(
    user_message: str,
    response: str,
    *,
    github_token: str,
    session_id: str | None = None,
    metrics: dict[str, float] | None = None,
    tool_calls: list | None = None,
    error: str | Exception | None = None,
    provider: BaseProvider | None = None,
    repo_path: str = ".",
    tests_dir: str = "tests",
    base_branch: str = "main",
) -> str:
    """Analyze a failed execution, commit a regression test, and open a GitHub PR.

    Wraps generate_regression_test() with git branch creation, commit, push,
    and PR creation. Requires a GitHub personal access token with repo scope.

    Args:
        user_message: The original input sent to the agent.
        response: The agent's response text.
        github_token: GitHub personal access token (repo scope).
        session_id: Optional session identifier — used in branch name, file name, and PR title.
        metrics: Optional timing metrics.
        tool_calls: Optional list of ToolCall objects.
        error: Optional error that occurred during execution.
        provider: LLM provider for analysis. Falls back to configure(provider=...).
        repo_path: Local path to the git repository. Defaults to current directory.
        tests_dir: Directory to write the test file into. Defaults to "tests".
        base_branch: Branch to open the PR against. Defaults to "main".

    Returns:
        The URL of the created GitHub PR.
    """
    safe = _safe_id(session_id)
    # Always append a timestamp so re-runs of the same session don't collide
    branch = f"trial/regression/{safe}-{_unique_branch_suffix()}"
    filename = f"test_regression_{safe}.py"
    file_path = os.path.join(repo_path, tests_dir, filename)

    # Ensure tests directory exists
    os.makedirs(os.path.join(repo_path, tests_dir), exist_ok=True)

    # Generate the test file
    generate_regression_test(
        user_message=user_message,
        response=response,
        session_id=session_id,
        metrics=metrics,
        tool_calls=tool_calls,
        error=error,
        provider=provider,
        output_path=file_path,
    )

    # Detect GitHub owner/repo from remote
    owner, repo = _get_github_repo(repo_path)

    # Create branch, commit, push
    _git(["checkout", "-b", branch], repo_path)
    _git(["add", file_path], repo_path)
    _git(
        ["commit", "-m", f"regression: add test for session {session_id or 'unknown'}"],
        repo_path,
    )
    _git(["push", "-u", "origin", branch], repo_path)

    # Open the PR
    title = f"Regression test: session {session_id}" if session_id else "Regression test"
    pr_body = (
        f"Automated regression test generated by [trial](https://github.com/mtc-tech-org/trial-py).\n\n"
        f"**Session:** `{session_id or 'unknown'}`\n\n"
        f"**Test file:** `{os.path.join(tests_dir, filename)}`\n\n"
        f"Before merging, replace `your_agent(USER_MSG)` in the test file with your actual agent call."
    )

    pr_url = _create_github_pr(
        owner=owner,
        repo=repo,
        token=github_token,
        head=branch,
        base=base_branch,
        title=title,
        body=pr_body,
    )

    return pr_url
