from __future__ import annotations

import json
import re
from typing import TYPE_CHECKING

from .config import get_provider

if TYPE_CHECKING:
    from .providers.base import BaseProvider
    from .tools import ToolCall


_ANALYSIS_SYSTEM_PROMPT = """You are an expert at analyzing AI agent failures and generating test criteria.

Given an agent execution (user message, response, error, metrics, tool calls), identify:
1. What went wrong — concise, human-readable
2. A judge criterion that would catch this failure in future runs
3. Whether a no_errors() check is appropriate (true if an error was present)
4. Whether a latency check is appropriate (true if elapsed_time is present and suspiciously high)

Be specific in the judge criterion — it should describe the correct behavior, not just "no errors".

Return JSON only — no extra text, no markdown fences:
{"failure_description": string, "judge_criterion": string, "include_no_errors": bool, "include_latency": bool, "latency_threshold": float | null}"""

_ANALYSIS_USER_TEMPLATE = """User message:
{user_message}

Agent response:
{response}

Error: {error}

Metrics: {metrics}

Tool calls: {tool_calls}

Analyze this execution and return JSON describing what went wrong and what assertions would catch it."""

_TEST_TEMPLATE = '''\
# Regression test — generated by trial
# Session: {session_comment}
# Failure: {failure_description}
#
# Replace `your_agent(USER_MSG)` with your actual agent call before running.

import pytest
from trial import Trial, configure
from trial.providers import AnthropicProvider

configure(provider=AnthropicProvider(model="claude-sonnet-4-6"))

USER_MSG = {user_message_repr}


def {test_fn_name}():
    response = your_agent(USER_MSG)  # TODO: replace with your agent

    result = (
        Trial.from_execution(
            user_message=USER_MSG,
            response=response,
        )
{checks}\
        .passes_judge(
            {judge_criterion_repr}
        )
        .run()
    )
    result.assert_passed()
'''


def _safe_id(session_id: str | None) -> str:
    if not session_id:
        return "session"
    return re.sub(r"[^a-zA-Z0-9]", "_", session_id)


def _render_test(
    user_message: str,
    session_id: str | None,
    failure_description: str,
    judge_criterion: str,
    include_no_errors: bool,
    include_latency: bool,
    latency_threshold: float | None,
) -> str:
    checks = ""
    if include_no_errors:
        checks += "        .no_errors()\n"
    if include_latency and latency_threshold is not None:
        checks += f"        .completes_within({latency_threshold})\n"

    return _TEST_TEMPLATE.format(
        session_comment=session_id or "unknown",
        failure_description=failure_description,
        user_message_repr=repr(user_message),
        test_fn_name=f"test_regression_{_safe_id(session_id)}",
        checks=checks,
        judge_criterion_repr=repr(judge_criterion),
    )


def generate_regression_test(
    user_message: str,
    response: str,
    *,
    session_id: str | None = None,
    metrics: dict[str, float] | None = None,
    tool_calls: list | None = None,
    error: str | Exception | None = None,
    provider: BaseProvider | None = None,
    output_path: str | None = None,
) -> str:
    """Analyze a failed execution and generate a pytest regression test.

    Uses an LLM to understand what went wrong and produce appropriate
    assertions. Returns the generated test source as a string.

    Args:
        user_message: The original input sent to the agent.
        response: The agent's response text.
        session_id: Optional identifier included in the test name and header comment.
        metrics: Optional timing metrics (e.g. {"elapsed_time": 12.4}).
        tool_calls: Optional list of ToolCall objects from the execution.
        error: Optional error that occurred during execution.
        provider: LLM provider for analysis. Falls back to configure(provider=...).
        output_path: If given, write the generated file to this path.

    Returns:
        The generated Python test source as a string.
    """
    error_str: str | None = str(error) if error is not None else None
    provider = provider or get_provider()

    tool_calls_summary = (
        [{"name": tc.name, "input": tc.input} for tc in tool_calls]
        if tool_calls
        else []
    )

    user_prompt = _ANALYSIS_USER_TEMPLATE.format(
        user_message=user_message,
        response=response,
        error=error_str or "none",
        metrics=json.dumps(metrics or {}),
        tool_calls=json.dumps(tool_calls_summary),
    )

    raw = provider.complete(system=_ANALYSIS_SYSTEM_PROMPT, user=user_prompt)

    try:
        data = json.loads(raw)
    except json.JSONDecodeError as e:
        raise ValueError(f"Analysis returned malformed JSON: {e}\nRaw: {raw!r}")

    required = {"failure_description", "judge_criterion", "include_no_errors", "include_latency"}
    missing = required - data.keys()
    if missing:
        raise ValueError(f"Analysis response missing fields: {missing}\nRaw: {raw!r}")

    code = _render_test(
        user_message=user_message,
        session_id=session_id,
        failure_description=str(data["failure_description"]),
        judge_criterion=str(data["judge_criterion"]),
        include_no_errors=bool(data["include_no_errors"]),
        include_latency=bool(data["include_latency"]),
        latency_threshold=data.get("latency_threshold"),
    )

    if output_path:
        with open(output_path, "w") as f:
            f.write(code)

    return code
